### PR TITLE
Features/v0.2

### LINKED ISSUE #5: qe_redacted Path wrong in 1_setup.sh
If your folders are being built outside the repository folder here is the fix:

RM Lines 72 and 73 in 1_setup.sh
    
72 # Move to parent directory
73 cd ..

### LINKED ISSUE #6: QE_REDACTED | Add to setup script
Add to line 955 in 1_setup.sh

NEAR_ACCOUNT_ID=your-account-name.testnet
NEAR_NETWORK=testnet
NEAR_CONTRACT_NAME=flexnetgx.testnet

### PR DESCRIPTION
**Pull request by KitBaroness**
Added a docker for users on strange operating systems... or just wanted to create a clean separate environment
Included a docker or standalone installation readme 
Update bug fix #5 
Update bug fix #6

### CODE REVIEW

**Review by Christopher-KT — COMMENTED** [review]
I don't see any obvious errors

**Review by Christopher-KT — APPROVED** [review]
Approved

**Review by klllj0ylife — APPROVED** [review]
done

**Review by Christopher-KT — APPROVED** [review]
Approved again?

**Comment by Christopher-KT** [comment]
Merge merge merge

**Pull request merged**
